version: '3.7'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /root/JackNorthon/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    container_name: front
  back:
    hostname: yourhockey
    build:
      context: ../YouHockey
      dockerfile: Dockerfile
    ports:
    - 8082:8082
    container_name: back
