version: '3.7'
services:
  front:
    build:
      context: /root/JackNorthon
      dockerfile: Dockerfile
    volumes:
      - /root/JackNorthon/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    container_name: front
  back:
    build:
      context: /root/Project_GunMarket
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    container_name: back
