version: '3.7'
services:
  front:
    build:
      dockerfile: Dockerfile
    volumes:
      - /root/JackNorthon/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    container_name: front
  back:
    build:
      dockerfile: ../Project_GunMarket/Dockerfile
    ports:
    - 8080:8080
    container_name: back
